In [1]:
my_list = [1,2,3,4]

In [2]:
my_list

[1, 2, 3, 4]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3, 4])

In [7]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [13]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [17]:
np.ones(2)

array([1., 1.])

In [20]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [19]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [21]:
np.linspace(0,5)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

In [22]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [23]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.random.rand(5)

array([0.05076039, 0.58219943, 0.08397264, 0.39052711, 0.83921568])

In [25]:
np.random.rand(5,5)

array([[0.59427318, 0.1235192 , 0.65643208, 0.21402702, 0.7819943 ],
       [0.29005748, 0.24674821, 0.77674982, 0.88197948, 0.31319597],
       [0.63496238, 0.06206457, 0.06942906, 0.73612775, 0.29496439],
       [0.89483722, 0.60203494, 0.12402367, 0.80046478, 0.63338714],
       [0.70902285, 0.75439659, 0.80636908, 0.8918514 , 0.07031575]])

In [26]:
np.random.randn(2)

array([-0.51311732,  0.22991922])

In [27]:
np.random.randn(4,4)

array([[ 1.06136002,  0.25113013, -1.803553  , -0.32400734],
       [ 1.89072831,  1.62901088,  0.30682453, -0.03515001],
       [ 1.87869907,  0.40177574,  1.94985278, -0.20791281],
       [ 0.42060849,  0.3460024 , -2.24124932, -0.18858503]])

In [30]:
np.random.randint(1,100)

4

In [31]:
np.random.randint(1,100,10)

array([73, 52, 27, 76, 55, 82, 73,  2, 49, 32])

In [32]:
arr = np.arange(25)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
ranarr = np.random.randint(0,50,10) 

In [35]:
ranarr

array([39,  7, 21, 22, 12, 34, 16, 28, 43, 47])

In [37]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [38]:
ranarr

array([39,  7, 21, 22, 12, 34, 16, 28, 43, 47])

In [39]:
ranarr.max()

47

In [40]:
ranarr.min()

7

In [41]:
ranarr.argmax()

9

In [42]:
ranarr.argmin()

1

In [44]:
arr.shape

(25,)

In [45]:
arr = arr.reshape(5,5)

In [46]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [47]:
arr.dtype

dtype('int32')

In [48]:
from numpy.random import randint

In [49]:
randint(2,10)

2