In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [7]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [9]:
arr[:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [11]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[0:5]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [15]:
slice_of_arr[:]

array([0, 1, 2, 3, 4])

In [16]:
slice_of_arr[:] = 99

In [17]:
slice_of_arr

array([99, 99, 99, 99, 99])

In [18]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [19]:
arr_copy = arr.copy()

In [20]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [21]:
arr_copy

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy[:] = 100

In [23]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [24]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [25]:
arr_2d = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr_2d[0][0]

1

In [28]:
arr_2d[0]

array([1, 2, 3])

In [29]:
arr_2d[1][1]

5

In [30]:
arr_2d[0,2]

3

In [32]:
arr_2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [33]:
arr = np.arange(1,11)

In [34]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [36]:
bool_arr = arr > 5

In [37]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [38]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [39]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [40]:
arr[arr < 3]

array([1, 2])

In [41]:
arr_2d = np.arange(50).reshape(5,10)

In [42]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [45]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [46]:
arr = np.arange(0,11)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [49]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [50]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [51]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [52]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [53]:
1 / 0

ZeroDivisionError: division by zero

In [54]:
arr / arr

<ipython-input-54-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [55]:
arr ** arr

array([         1,          1,          4,         27,        256,
             3125,      46656,     823543,   16777216,  387420489,
       1410065408], dtype=int32)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [58]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [59]:
np.max(arr)

10

In [60]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [61]:
np.log(arr)

<ipython-input-61-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])